export const TIME_MACHINE_MANUAL_EDITORIAL_ENTRIES = [
  { year: 1800, hook: 'An Order Came Under Fire', teaser: '1800 United States presidential election and Papal conclave, 1799–1800: cardinal Barnaba Chiaramonti succeeds Pius shaped the year with conflict and political realignment.' },
  { year: 1801, hook: 'The Year Refused Calm', teaser: 'War of the Second Coalition and Toussaint Louverture triumphantly enters Santo Domingo, the capital shaped the year with military pressure and persistent instability.' },
  { year: 1802, hook: 'The Horizon Pulled Wider', teaser: 'Thomas Bruce, 7th Earl of Elgin and Haitian Revolution shaped the year with distance giving way to reach.' },
  { year: 1803, hook: 'Culture Moved Into View', teaser: 'Ludwig van Beethoven puts on a big Akademie and William Symington demonstrates his Charlotte Dundas, the "first shaped the year with cultural momentum.' },
  { year: 1804, hook: 'The Public Imagination Shifted', teaser: 'Cornishman Richard Trevithick\'s newly built Penydarren steam locomotive and Serbian Revolution shaped the year with a visible shift in public life.' },
  { year: 1805, hook: 'The Front Kept Moving', teaser: 'Continental Divide of the Americas and Battle of Diamond Rock shaped the year with war shaping the calendar.' },
  { year: 1806, hook: 'Discovery Pushed Forward', teaser: 'Lewis and Clark Expedition and Explorers Lewis and Clark and their Corps shaped the year with scientific momentum and outward ambition.' },
  { year: 1807, hook: 'Power Turned Harder', teaser: 'Chesapeake–Leopard affair: British Royal Navy fourth rate attacks and Abolitionism in the United Kingdom shaped the year with hard power and unstable order.' },
  { year: 1808, hook: 'The Story Kept Swerving', teaser: 'Transfer of the Portuguese court to Brazil and Rum Rebellion: On the 20th anniversary shaped the year with events refusing a neat pattern.' },
  { year: 1809, hook: 'Conflict Never Sat Still', teaser: 'Sweden promulgates a new Instrument of Government, which and Battle of Corunna shaped the year with conflict and volatile turns.' },
  { year: 1810, hook: 'The Year Refused Calm', teaser: 'Venezuela achieves home rule: Vicente Emparán, Governor and After seizing Jaén, Córdoba, Seville and Granada, Napoleonic shaped the year with military pressure and persistent instability.' },
  { year: 1811, hook: 'Rights Moved to the Fore', teaser: 'Luddite uprisings, in which workers destroy industrial machines and Battle of the Gebora shaped the year with rights moving into full view.' },
  { year: 1812, hook: 'Conflict Set the Pace', teaser: 'Battle of Borodino and Peninsular War shaped the year with military escalation.' },
  { year: 1813, hook: 'Power Turned Harder', teaser: 'Doctrine of the Trinity Act 1813 and Battle of Frenchtown shaped the year with hard power and unstable order.' },
  { year: 1814, hook: 'The Front Kept Moving', teaser: 'War of the Sixth Coalition and First Battle of Bar-sur-Aube shaped the year with war shaping the calendar.' },
  { year: 1815, hook: 'Nature Hit Without Warning', teaser: 'Mount Tambora in the Dutch East Indies blows and Treaty of Ghent shaped the year with sudden pressure.' },
  { year: 1816, hook: 'Power Turned Harder', teaser: 'Treaty of Sugauli and Friedrich Karl Ludwig, Duke of Schleswig-Holstein-Sonderburg-Beck shaped the year with hard power and unstable order.' },
  { year: 1817, hook: 'Tension Kept Breaking Loose', teaser: 'Battle of Chacabuco and Sailing through the Sandwich Islands, Otto von Kotzebue shaped the year with war and abrupt reversals.' },
  { year: 1818, hook: 'Conflict Never Sat Still', teaser: 'Third Anglo-Maratha War and Upon his death, King Charles XIII of Sweden shaped the year with conflict and volatile turns.' },
  { year: 1819, hook: 'Authority Changed Hands', teaser: '1819 Singapore Treaty and United States House of Representatives shaped the year with authority shifting in plain sight.' },
  { year: 1820, hook: 'The Story Kept Swerving', teaser: 'The last judicial decapitation in the United Kingdom and A constitutionalist military insurrection at Cádiz leads shaped the year with events refusing a neat pattern.' },
  { year: 1821, hook: 'Conflict Never Sat Still', teaser: 'Egyptian conquest of Sudan: King Badi VII and Peter I Island in the Antarctic is first shaped the year with conflict and volatile turns.' },
  { year: 1822, hook: 'Distance Started to Shrink', teaser: 'The American Colonization Society lands at Cape Mesurado and The Portuguese prince Pedro I of Brazil decides shaped the year with expanding horizons.' },
  { year: 1823, hook: 'The Order Started to Shift', teaser: 'By secret treaty signed at the Congress and In Paviland Cave on the Gower Peninsula shaped the year with power changing hands.' },
  { year: 1824, hook: 'Frontiers Kept Moving', teaser: 'Mission Santa Inés and The Mechanics\' Institution is established in Manchester, England shaped the year with outward ambition.' },
  { year: 1825, hook: 'Authority Changed Hands', teaser: '1824 United States presidential election and Ferdinand I of the Two Sicilies shaped the year with authority shifting in plain sight.' },
  { year: 1826, hook: 'The Story Kept Swerving', teaser: 'The Ballantyne printing business in Edinburgh crashes and Siege of Bharatpur shaped the year with events refusing a neat pattern.' },
  { year: 1827, hook: 'Conflict Never Sat Still', teaser: 'Furman University, founded in 1826, begins its first and The first regatta in Australia is held, taking shaped the year with conflict and volatile turns.' },
  { year: 1828, hook: 'The Year Refused Calm', teaser: 'Black War and Arthur Wellesley, 1st Duke of Wellington shaped the year with military pressure and persistent instability.' },
  { year: 1829, hook: 'Tension Kept Breaking Loose', teaser: 'German composer Felix Mendelssohn conducts the first performance and August Klingemann\'s adaptation of Johann Wolfgang von Goethe\'s shaped the year with war and abrupt reversals.' },
  { year: 1830, hook: 'Conflict Never Sat Still', teaser: 'Joseph Smith and five others organize the Church and Webster–Hayne debate: In the United States Congress, Robert shaped the year with conflict and volatile turns.' },
  { year: 1831, hook: 'Nothing Held Still for Long', teaser: 'Global financial services business Assicurazioni Generali is founded and William Lloyd Garrison begins publishing The Liberator shaped the year with constant instability.' },
  { year: 1832, hook: 'Public Pressure Held', teaser: 'The Reform Act receives royal assent after passage and The Christmas Rebellion of slaves is brought shaped the year with collective pressure and civic change.' },
  { year: 1833, hook: 'Conflict Never Sat Still', teaser: 'Antonio López de Santa Anna and At least 170 people—and perhaps as many as shaped the year with conflict and volatile turns.' },
  { year: 1834, hook: 'Nothing Held Still for Long', teaser: 'William Lamb, 2nd Viscount Melbourne and Freed American slaves from Maryland form a settlement shaped the year with constant instability.' },
  { year: 1835, hook: 'Instability Came in Waves', teaser: 'Attempted assassination of Andrew Jackson and anchors off the Chonos Archipelago on her second shaped the year with pressure without much warning.' },
  { year: 1836, hook: 'An Order Came Under Fire', teaser: 'Texas Revolution and Battle of the Alamo shaped the year with conflict and political realignment.' },
  { year: 1837, hook: 'The Public Pushed Back', teaser: 'The Congregation of Holy Cross is formed and In Philadelphia, the Institute for Colored Youth shaped the year with organised civic demand.' },
  { year: 1838, hook: 'The Order Started to Shift', teaser: 'U and At Morristown, New Jersey, Samuel Morse, Alfred Vail shaped the year with power changing hands.' },
  { year: 1839, hook: 'Power Moved Quickly', teaser: 'Treaty of London and Battle of Yungay shaped the year with political realignment.' },
  { year: 1840, hook: 'Distance Started to Shrink', teaser: 'United States Exploring Expedition and Jules Dumont d\'Urville discovers Adélie Land in Antarctica shaped the year with expanding horizons.' },
  { year: 1841, hook: 'A New Mood Took Hold', teaser: 'The ballet Giselle is first presented by and Charles Elliot of the United Kingdom and Qishan shaped the year with a changing public imagination.' },
  { year: 1842, hook: 'Conflict Never Sat Still', teaser: 'First Anglo-Afghan War and Antarctic explorer James Clark Ross, charting the eastern shaped the year with conflict and volatile turns.' },
  { year: 1843, hook: 'The Year Refused Calm', teaser: 'Marc Isambard Brunel\'s Thames Tunnel, the first tunnel and Illustrated Treatise on the Maritime Kingdoms shaped the year with military pressure and persistent instability.' },
  { year: 1844, hook: 'Tension Kept Breaking Loose', teaser: 'A gun on the USS Princeton explodes while and Persian prophet The Báb privately announces his revelation shaped the year with war and abrupt reversals.' },
  { year: 1845, hook: 'The Year Refused a Pattern', teaser: 'Captaincy General of the Philippines and Elizabeth Barrett receives a love letter from shaped the year with unpredictable turns.' },
  { year: 1846, hook: 'Nothing Held Still for Long', teaser: 'Texas annexation: United States president James K and The Milan–Venice railway\'s bridge, over the Venetian Lagoon shaped the year with constant instability.' },
  { year: 1847, hook: 'Tension Kept Breaking Loose', teaser: 'Battle of Buena Vista and The world\'s first municipally-funded civic public park, Birkenhead shaped the year with war and abrupt reversals.' },
  { year: 1848, hook: 'The Year Refused a Pattern', teaser: 'Prince Philippe, Count of Paris and Hungarian Revolution of 1848 shaped the year with unpredictable turns.' },
  { year: 1849, hook: 'The Year Refused Calm', teaser: 'Regular steamboat service from the west and Hungarian Revolution of 1848 shaped the year with military pressure and persistent instability.' },
  { year: 1850, hook: 'Progress Faced the Elements', teaser: 'The ship Elizabeth, an American merchant freighter carrying and Henry Clay introduces the Compromise of 1850 shaped the year with shock and technical ambition.' },
  { year: 1851, hook: 'The Year Refused a Pattern', teaser: 'Herman Melville\'s novel Moby-Dick and The flip of a coin, subsequently named shaped the year with unpredictable turns.' },
  { year: 1852, hook: 'Distance Started to Shrink', teaser: 'After learning that U and President Louis-Napoléon Bonaparte proclaims a new constitution shaped the year with expanding horizons.' },
  { year: 1853, hook: 'Instability Came in Waves', teaser: 'Prince Leopold, the youngest son and the eighth and Taiping Rebellion: Zeng Guofan is ordered to assist shaped the year with pressure without much warning.' },
  { year: 1854, hook: 'The Year Refused a Pattern', teaser: 'Atlantic and North Carolina Railroad and Texas is linked by telegraph with the rest shaped the year with unpredictable turns.' },
  { year: 1855, hook: 'The Year Refused Calm', teaser: 'In Australia, the province of Victoria (named and Crimean War shaped the year with military pressure and persistent instability.' },
  { year: 1856, hook: 'Rights Moved to the Fore', teaser: 'Taiping Rebellion: Suspecting treachery on the part and American clipper ships Driver and Ocean Queen leave shaped the year with rights moving into full view.' },
  { year: 1857, hook: 'Conflict Never Sat Still', teaser: 'The University of Calcutta is established in Calcutta and The biggest Estonian newspaper, Postimees, is established by shaped the year with conflict and volatile turns.' },
  { year: 1858, hook: 'Nothing Held Still for Long', teaser: 'Orsini affair: Piedmontese revolutionary Felice Orsini and his and The Wedding March by Felix Mendelssohn becomes shaped the year with constant instability.' },
  { year: 1859, hook: 'The Story Kept Swerving', teaser: 'German scholar Constantin von Tischendorf rediscovers the Codex and Siege of Saigon shaped the year with events refusing a neat pattern.' },
  { year: 1860, hook: 'The Year Refused a Pattern', teaser: 'Sakuradamon Incident and The astronomer Urbain Le Verrier announces the discovery shaped the year with unpredictable turns.' },
  { year: 1861, hook: 'Nothing Held Still for Long', teaser: 'Alexander Stephens, Vice President of the Confederacy, gives and Tsushima incident shaped the year with constant instability.' },
  { year: 1862, hook: 'The Front Kept Moving', teaser: 'Great Locomotive Chase – Union volunteers and November 1 – The 1862 International Exhibition is shaped the year with war shaping the calendar.' },
  { year: 1863, hook: 'Conflict Set the Pace', teaser: 'American Civil War and The January Uprising breaks out in Poland, Lithuania shaped the year with military escalation.' },
  { year: 1864, hook: 'The Public Pushed Back', teaser: 'American songwriter Stephen Foster ("Oh! Susanna", "Old Folks and Second Schleswig War shaped the year with organised civic demand.' },
  { year: 1865, hook: 'The Front Kept Moving', teaser: 'Edward Canby and Second Battle of Fort Fisher shaped the year with war shaping the calendar.' },
  { year: 1866, hook: 'Demands Reached the Streets', teaser: 'Civil Rights Act of 1866 and Ottoman troops clash with supporters of Maronite leader shaped the year with public pressure and political reckoning.' },
  { year: 1867, hook: 'Nothing Held Still for Long', teaser: 'The Covington–Cincinnati Suspension Bridge opens between Cincinnati, Ohio and The late Emperor Kōmei\'s 14-year-old son, Prince Mutsuhito shaped the year with constant instability.' },
  { year: 1868, hook: 'The Front Kept Moving', teaser: 'Boshin War and Paraguayan War shaped the year with war shaping the calendar.' },
  { year: 1869, hook: 'The Streets Refused Silence', teaser: 'The first transcontinental railroad in North America is and The Republic of Ezo is proclaimed shaped the year with public pressure.' },
  { year: 1870, hook: 'The Crowd Wanted More', teaser: 'Reconstruction Era: Virginia rejoins the Union and A political cartoon for the first time symbolizes shaped the year with mass demands and contested authority.' },
  { year: 1871, hook: 'The Horizon Pulled Wider', teaser: 'Proclamation of the German Empire and Battle of Dijon shaped the year with distance giving way to reach.' },
  { year: 1872, hook: 'The Year Refused a Pattern', teaser: 'Filipino priests José Burgos, Mariano Gomez and Jacinto and Grand Duke Alexei Alexandrovich of Russia shaped the year with unpredictable turns.' },
  { year: 1873, hook: 'The Year Refused Calm', teaser: 'American Indian Wars and First Battle of the Stronghold shaped the year with military pressure and persistent instability.' },
  { year: 1874, hook: 'Tension Kept Breaking Loose', teaser: 'Grand Duchess Maria Alexandrovna of Russia and Third Carlist War shaped the year with war and abrupt reversals.' },
  { year: 1875, hook: 'The Year Refused a Pattern', teaser: 'The majority of the Yavapai and Tonto and The Midland Railway of England abolishes the Second shaped the year with unpredictable turns.' },
  { year: 1876, hook: 'Power Turned Harder', teaser: 'Japan–Korea Treaty of 1876 and The first stage production of the verse-play Peer shaped the year with hard power and unstable order.' },
  { year: 1877, hook: 'The Order Started to Shift', teaser: '1876 United States presidential election and Queen Victoria is proclaimed Empress of India by shaped the year with power changing hands.' },
  { year: 1878, hook: 'The Year Refused a Pattern', teaser: 'November 10 – Exposition Universelle, a world\'s fair and Russian revolutionary Vera Zasulich shoots at Fyodor Trepov shaped the year with unpredictable turns.' },
  { year: 1879, hook: 'Distance Started to Shrink', teaser: 'William Denny and Brothers launch the world\'s first and Battle of Isandlwana shaped the year with expanding horizons.' },
  { year: 1880, hook: 'The Story Kept Swerving', teaser: 'For the first and last time in its and Thomas Edison is granted a patent shaped the year with events refusing a neat pattern.' },
  { year: 1881, hook: 'Conflict Never Sat Still', teaser: 'William Edward Forster and Carlos Finlay introduces his discovery of the transmission shaped the year with conflict and volatile turns.' },
  { year: 1882, hook: 'Power Turned Harder', teaser: 'Charles Stewart Parnell and British gunboats enter Monrovia, with Arthur Havelock demanding shaped the year with hard power and unstable order.' },
  { year: 1883, hook: 'Rights Moved to the Fore', teaser: 'Demonstration of 9 March 1883 and Battle of Gia Cuc shaped the year with rights moving into full view.' },
  { year: 1884, hook: 'The Streets Refused Silence', teaser: 'William Price attempts to cremate his dead baby and Siege of Khartoum shaped the year with public pressure.' },
  { year: 1885, hook: 'War Darkened the Calendar', teaser: 'United States Army Corps of Engineers and Battle of Núi Bop shaped the year with conflict setting the tempo.' },
  { year: 1886, hook: 'Tension Kept Breaking Loose', teaser: 'President of the United States and Third Anglo-Burmese War shaped the year with war and abrupt reversals.' },
  { year: 1887, hook: 'Frontiers Kept Moving', teaser: 'Hibernian F and Interstate Commerce Act of 1887 shaped the year with outward ambition.' },
  { year: 1888, hook: 'Nothing Held Still for Long', teaser: 'Year of the Three Emperors and The Schoolhouse Blizzard hits Dakota Territory shaped the year with constant instability.' },
  { year: 1889, hook: 'Rights Moved to the Fore', teaser: 'Battle of Metemma: Yohannes IV, Emperor of Ethiopia and Mayerling incident shaped the year with rights moving into full view.' },
  { year: 1890, hook: 'Conflict Never Sat Still', teaser: 'The United States Census Bureau begins using Herman and 1890 British Ultimatum: The United Kingdom demands Portugal shaped the year with conflict and volatile turns.' },
  { year: 1891, hook: 'The Year Refused Calm', teaser: 'In the FA Cup quarter final in English and In New Orleans, a lynch mob storms shaped the year with military pressure and persistent instability.' },
  { year: 1892, hook: 'The Story Kept Swerving', teaser: 'Exclusive Agreement: Rulers of six Trucial States (Abu and Theodoros Deligiannis ends his term as Prime Minister shaped the year with events refusing a neat pattern.' },
  { year: 1893, hook: 'The Year Refused a Pattern', teaser: 'Overthrow of the Kingdom of Hawaii: Lorrin and The Tati Concessions Land, formerly part of Matabeleland shaped the year with unpredictable turns.' },
  { year: 1894, hook: 'Nothing Held Still for Long', teaser: 'Café Terminus attack and A military alliance is established between the French shaped the year with constant instability.' },
  { year: 1895, hook: 'The Front Kept Moving', teaser: 'Dreyfus affair: French officer Alfred Dreyfus is stripped and The Wilcox rebellion, an attempt led by Robert shaped the year with war shaping the calendar.' },
  { year: 1896, hook: 'Frontiers Kept Moving', teaser: 'Archaeologist Alois Anton Führer, Nepalese General Khadga Samsher and Anglo-Ashanti wars shaped the year with outward ambition.' },
  { year: 1897, hook: 'Knowledge Moved Ahead', teaser: 'J and Lady Flora Shaw, future wife of Governor General shaped the year with knowledge moving into action.' },
  { year: 1898, hook: 'Tension Kept Breaking Loose', teaser: 'New York City annexes land from surrounding counties and Novelist Émile Zola\'s open letter to the President shaped the year with war and abrupt reversals.' },
  { year: 1899, hook: 'The Year Refused a Pattern', teaser: 'The February Manifesto is issued by the Emperor and The research vessel SS Southern Cross shaped the year with unpredictable turns.' },
  { year: 1900, hook: 'War and Knowledge Converged', teaser: 'Nobel Prize in Physiology or Medicine and Southern Cross Expedition shaped the year with scientific momentum under wartime pressure.' },
  { year: 1901, hook: 'Tension Kept Breaking Loose', teaser: 'Queen Victoria of the United Kingdom dies and Lord Kitchener reports that Christiaan de Wet has shaped the year with war and abrupt reversals.' },
  { year: 1902, hook: 'A Year of Reach and Rupture', teaser: 'Pax airship disaster and A train collision in the New York Central shaped the year with catastrophe and outward ambition.' },
  { year: 1903, hook: 'The Year Refused Calm', teaser: '21 (April 6–8 O and Aceh War shaped the year with military pressure and persistent instability.' },
  { year: 1904, hook: 'Tension Kept Breaking Loose', teaser: 'The Geographical Pivot of History and Battle of Port Arthur shaped the year with war and abrupt reversals.' },
  { year: 1905, hook: 'The Year Refused a Pattern', teaser: 'The Dominican Republic signs an agreement with and U shaped the year with unpredictable turns.' },
  { year: 1906, hook: 'Authority Changed Hands', teaser: 'Persian Constitutional Revolution and Karl Staaff steps down as Prime Minister shaped the year with authority shifting in plain sight.' },
  { year: 1907, hook: 'The Order Started to Shift', teaser: 'Elections to the new Parliament of Finland are and 1907 Kingston earthquake shaped the year with power changing hands.' },
  { year: 1908, hook: 'The Year Refused a Pattern', teaser: 'American diplomat Durham Stevens, an employee of Japan\'s and Prime Minister of the United Kingdom shaped the year with unpredictable turns.' },
  { year: 1909, hook: 'Distance Started to Shrink', teaser: 'Nimrod Expedition and Spanish–American War shaped the year with expanding horizons.' },
  { year: 1910, hook: 'The Order Started to Shift', teaser: 'January 1910 United Kingdom general election and Chinese expedition to Tibet: A force of 2,000 shaped the year with power changing hands.' },
  { year: 1911, hook: 'The Year Refused a Pattern', teaser: 'In American baseball, the Philadelphia Athletics defeat and Terra Nova Expedition shaped the year with unpredictable turns.' },
  { year: 1912, hook: 'The Crowd Wanted More', teaser: 'The African National Congress is founded as and Battle of Beirut shaped the year with mass demands and contested authority.' },
  { year: 1913, hook: 'Tension Kept Breaking Loose', teaser: 'Princess Victoria Louise of Prussia and Pavlos Kountouriotis shaped the year with war and abrupt reversals.' },
  { year: 1914, hook: 'Conflict Never Sat Still', teaser: 'The St and Tsar Nicholas II of Russia dismisses his 4th shaped the year with conflict and volatile turns.' },
  { year: 1915, hook: 'Invention Left a Mark', teaser: 'The first United States coast-to-coast long-distance telephone call and Chilembwe uprising: Baptist minister John Chilembwe initiates shaped the year with new tools entering daily life.' },
  { year: 1916, hook: 'The Front Kept Moving', teaser: 'Mexican Revolution and WWI: Gallipoli Campaign – The last British troops shaped the year with war shaping the calendar.' },
  { year: 1917, hook: 'Conflict Never Sat Still', teaser: '"Livery Stable Blues", recorded with "Dixie Jazz Band and WWI: Army transport fires the United States\' first shaped the year with conflict and volatile turns.' },
  { year: 1918, hook: 'War Darkened the Calendar', teaser: 'Battle of Tell \'Asur and The Three Minute Pause, initiated by the daily shaped the year with conflict setting the tempo.' },
  { year: 1919, hook: 'A New Mood Took Hold', teaser: 'The Faisal–Weizmann Agreement is signed by Emir Faisal and 1918 United Kingdom general election in Ireland shaped the year with a changing public imagination.' },
  { year: 1920, hook: 'Demands Reached the Streets', teaser: 'Svalbard Treaty and The Netherlands refuses to extradite ex-German Emperor Wilhelm shaped the year with public pressure and political reckoning.' },
  { year: 1921, hook: 'Power Turned Harder', teaser: 'The Emergency Quota Act is passed by and The full-length silent comedy drama film The Kid shaped the year with hard power and unstable order.' },
  { year: 1922, hook: 'The Balance Broke Open', teaser: 'Supreme Court of the United States and Edward VIII shaped the year with warfare and reshaped authority.' },
  { year: 1923, hook: 'The Year Refused a Pattern', teaser: 'Australian cricketer Bill Ponsford makes 429 runs and Billy Hughes, having resigned as Prime Minister shaped the year with unpredictable turns.' },
  { year: 1924, hook: 'Nothing Held Still for Long', teaser: 'The Ottoman Caliphate, a remnant of the Ottoman and Kuomintang in China holds its first National Congress shaped the year with constant instability.' },
  { year: 1925, hook: 'The Story Kept Swerving', teaser: 'The Tri-State Tornado, the deadliest in U and The Syrian Federation is officially dissolved, the State shaped the year with events refusing a neat pattern.' },
  { year: 1926, hook: 'Frontiers Kept Moving', teaser: 'El Virilla train accident in Costa Rica: 385 and Scottish inventor John Logie Baird demonstrates a mechanical shaped the year with outward ambition.' },
  { year: 1927, hook: 'Ambition Met Upheaval', teaser: 'Nanking incident of 1927 and Academy of Motion Picture Arts and Sciences shaped the year with disaster and modern reach.' },
  { year: 1928, hook: 'The Story Kept Swerving', teaser: 'Pineapple Primary: The United States Republican Party primary and The 1928 Winter Olympics are held in St shaped the year with events refusing a neat pattern.' },
  { year: 1929, hook: 'Conflict Set the Pace', teaser: 'Warlord Rebellion in northeastern Shandong and "Litvinov\'s Pact" is signed in Moscow by shaped the year with military escalation.' },
  { year: 1930, hook: 'Nothing Held Still for Long', teaser: 'The government of Turkey requests the international community and Mahatma Gandhi sets off on a 200-mile march shaped the year with constant instability.' },
  { year: 1931, hook: 'A New Mood Took Hold', teaser: 'Charlie Chaplin comedy drama film City Lights receives and Soviet leader Joseph Stalin gives a speech calling shaped the year with a changing public imagination.' },
  { year: 1932, hook: 'The Year Refused a Pattern', teaser: 'Sakuradamon Incident: Korean nationalist Lee Bong-chang fails and Hattie W shaped the year with unpredictable turns.' },
  { year: 1933, hook: 'Nothing Held Still for Long', teaser: '"Pakistan Declaration": Choudhry Rahmat Ali publishes (in Cambridge and A mutiny starts on the Royal Netherlands Navy shaped the year with constant instability.' },
  { year: 1934, hook: 'The Order Started to Shift', teaser: '1934 Australian federal election and French political crisis: The French far-right leagues rally shaped the year with power changing hands.' },
  { year: 1935, hook: 'Discovery Changed the Tempo', teaser: 'The discovery and clinical development of Prontosil and Italian premier Benito Mussolini and French Foreign Minister shaped the year with scientific momentum.' },
  { year: 1936, hook: 'Distance Started to Shrink', teaser: 'Montreux Convention Regarding the Regime of the Straits and Treaty of Versailles shaped the year with expanding horizons.' },
  { year: 1937, hook: 'Rights Moved to the Fore', teaser: 'Moscow Trials: Trial of the Anti-Soviet Trotskyist Center and The Moscow Trial initiated on January 23 is shaped the year with rights moving into full view.' },
  { year: 1938, hook: 'Conflict Never Sat Still', teaser: 'No evidence of German troop movements against Czechoslovakia and Chancellor Kurt von Schuschnigg of Austria meets Adolf shaped the year with conflict and volatile turns.' },
  { year: 1939, hook: 'Power Turned Harder', teaser: 'Adolf Hitler orders Plan Z, a 5-year naval and Daughters of the American Revolution shaped the year with hard power and unstable order.' },
  { year: 1940, hook: 'Tension Kept Breaking Loose', teaser: 'Katyn massacre and Jallianwala Bagh massacre shaped the year with war and abrupt reversals.' },
  { year: 1941, hook: 'Conflict Never Sat Still', teaser: 'WWII: Three Nights\' Blitz over Swansea, South Wales and Franklin D shaped the year with conflict and volatile turns.' },
  { year: 1942, hook: 'War Darkened the Calendar', teaser: 'American film actress Carole Lombard and her mother and WWII: South African forces of the British 8th shaped the year with conflict setting the tempo.' },
  { year: 1943, hook: 'War Darkened Every Horizon', teaser: 'From Majdanek and the Roman Ghetto to Sobibor\'s revolt and the strike on Bari, the year reads as a chronology of industrial war and organized annihilation.' },
  { year: 1944, hook: 'The Endgame Grew Louder', teaser: 'Allied advances reached Aachen and Leyte, Tirpitz and Musashi were destroyed, and Hanford\'s B Reactor hinted that the war was already changing the future of power itself.' },
  { year: 1945, hook: 'War Darkened the Calendar', teaser: '22 – At the Grünhagen railroad station and Allies of World War II shaped the year with conflict setting the tempo.' },
  { year: 1946, hook: 'Tension Kept Breaking Loose', teaser: 'Manhattan Project physicist Louis Slotin accidentally triggers and ENIAC shaped the year with war and abrupt reversals.' },
  { year: 1947, hook: 'The Year Refused a Pattern', teaser: 'A KLM Douglas DC-3 aircraft crashes soon after and Socialist Federal Republic of Yugoslavia shaped the year with unpredictable turns.' },
  { year: 1948, hook: 'The Crowd Wanted More', teaser: 'Treaty of Brussels and Burma gains its independence from the United Kingdom shaped the year with mass demands and contested authority.' },
  { year: 1949, hook: 'The Story Kept Swerving', teaser: 'The first VW Type 1 to arrive and A United Nations-sponsored ceasefire brings an end shaped the year with events refusing a neat pattern.' },
  { year: 1950, hook: 'Shock Kept Arriving', teaser: 'Sverdlovsk plane crash: Aeroflot Lisunov Li-2 crashes and Cold War shaped the year with repeated shock and sudden turns.' },
  { year: 1951, hook: 'Power Turned Harder', teaser: '1951 Australian federal election and Second Battle of Seoul shaped the year with hard power and unstable order.' },
  { year: 1952, hook: 'Rights Moved to the Fore', teaser: 'In Dhaka, East Pakistan police open and A Douglas C-47 Dakota operated by Aer Lingus shaped the year with rights moving into full view.' },
  { year: 1953, hook: 'Shock Kept Arriving', teaser: 'North Sea flood of 1953 and 71 shaped the year with repeated shock and sudden turns.' },
  { year: 1954, hook: 'The Year Refused Calm', teaser: 'First Indochina War and BOAC Flight 781, a de Havilland Comet jet shaped the year with military pressure and persistent instability.' },
  { year: 1955, hook: 'The Balance Broke Open', teaser: 'Claudette Colvin, a 15-year-old African-American girl, refuses and Battle of Yijiangshan Islands shaped the year with warfare and reshaped authority.' },
  { year: 1956, hook: 'Culture Moved Into View', teaser: 'Missionary and Nikita Khrushchev attacks the veneration of Joseph Stalin shaped the year with cultural momentum.' },
  { year: 1957, hook: 'Distance Started to Shrink', teaser: 'Juan Manuel Fangio, driving for Maserati, wins and South African player Russell Endean becomes the first shaped the year with expanding horizons.' },
  { year: 1958, hook: 'Tension Kept Breaking Loose', teaser: 'The Falcons aerobatic team of the Pakistan Air and Munich air disaster shaped the year with war and abrupt reversals.' },
  { year: 1959, hook: 'The Year Refused a Pattern', teaser: 'At a ceremony near Toddington, British Minister and Soviet lunar probe Luna 1 is the first shaped the year with unpredictable turns.' },
  { year: 1960, hook: 'The Crowd Wanted More', teaser: 'Treaty of Mutual Cooperation and Security between and Greensboro sit-ins: In Greensboro, North Carolina, four black shaped the year with mass demands and contested authority.' },
  { year: 1961, hook: 'The Story Kept Swerving', teaser: 'Following a four-day conference in Casablanca, five African and Ham, a 37-pound male chimpanzee, is rocketed shaped the year with events refusing a neat pattern.' },
  { year: 1962, hook: 'Shock Kept Arriving', teaser: 'American Airlines Flight 1 crashes and North Sea flood of 1962 shaped the year with repeated shock and sudden turns.' },
  { year: 1963, hook: 'Nothing Held Still for Long', teaser: 'Soviet spy Gheorghe Pintilie is removed from his and In Paris, six people are sentenced to death shaped the year with constant instability.' },
  { year: 1964, hook: 'The Story Kept Swerving', teaser: 'The Beatles perform for the first time and Non ho l\'età (music by Nicola Salerno, text shaped the year with events refusing a neat pattern.' },
  { year: 1965, hook: 'Conflict Set the Pace', teaser: 'Vietnam War and The state funeral of Sir Winston Churchill takes shaped the year with military escalation.' },
  { year: 1966, hook: 'The Year Refused Calm', teaser: 'Battle of Long Tan and Football\'s FIFA World Cup Trophy is stolen while shaped the year with military pressure and persistent instability.' },
  { year: 1967, hook: 'A New Mood Took Hold', teaser: 'A United Nations delegation arrives in Aden as and Montreal, Quebec, Expo 67, a World\'s Fair shaped the year with a changing public imagination.' },
  { year: 1968, hook: 'The Streets Refused Silence', teaser: 'Orangeburg Massacre and Vietnam War shaped the year with public pressure.' },
  { year: 1969, hook: 'The Year Took Heavy Blows', teaser: '1969 Santa Barbara oil spill and The body of former United States General shaped the year with disruption on a large scale.' },
  { year: 1970, hook: 'Instability Came in Waves', teaser: 'Ostpolitik: The leaders of West Germany and East and 1970 Tonghai earthquake shaped the year with pressure without much warning.' },
  { year: 1971, hook: 'The Year Refused a Pattern', teaser: 'A bomb made of two hand grenades by and Arab states of the Persian Gulf shaped the year with unpredictable turns.' },
  { year: 1972, hook: 'The Public Pushed Back', teaser: 'The Canadian ketch Vega, flying the Greenpeace III and Members of the Mukti Bahini lay down their shaped the year with organised civic demand.' },
  { year: 1973, hook: 'Tension Kept Breaking Loose', teaser: 'Libyan Arab Airlines Flight 114 is and The United Kingdom, the Republic of Ireland shaped the year with war and abrupt reversals.' },
  { year: 1974, hook: 'The Year Refused a Pattern', teaser: 'Turkish Airlines Flight 981, travelling from Paris and Edward Heath shaped the year with unpredictable turns.' },
  { year: 1975, hook: 'The Year Refused Calm', teaser: 'West German Embassy siege in Stockholm and Tasman Bridge disaster shaped the year with military pressure and persistent instability.' },
  { year: 1976, hook: 'Tension Kept Breaking Loose', teaser: 'The Boston Celtics defeat the Phoenix Suns 128–126 and A locomotive crashes into the rear shaped the year with war and abrupt reversals.' },
  { year: 1977, hook: 'Conflict Never Sat Still', teaser: 'German Federal Prosecutor Siegfried Buback and his driver and An Ejército del Aire CASA C-207C Azor (registration shaped the year with conflict and volatile turns.' },
  { year: 1978, hook: 'Power Turned Harder', teaser: 'Anwar Sadat and Northeastern United States blizzard of 1978 shaped the year with hard power and unstable order.' },
  { year: 1979, hook: 'Tension Kept Breaking Loose', teaser: 'Cambodian–Vietnamese War and Rod Stewart shaped the year with war and abrupt reversals.' },
  { year: 1980, hook: 'The Year Refused a Pattern', teaser: 'Victoria, Crown Princess of Sweden and Canadian Caper: Six United States diplomats, posing as shaped the year with unpredictable turns.' },
  { year: 1981, hook: 'The Ground Would Not Settle', teaser: 'In Greece, 20 fans of Olympiacos F and Iran releases the 52 Americans held for 444 shaped the year with instability and abrupt disruption.' },
  { year: 1982, hook: 'Progress Faced the Elements', teaser: 'Edwards Air Force Base and Air Florida Flight 90 crashes shortly after takeoff shaped the year with shock and technical ambition.' },
  { year: 1983, hook: 'The Year Refused a Pattern', teaser: 'Pope John Paul II appoints a bishop over and U shaped the year with unpredictable turns.' },
  { year: 1984, hook: 'The Public Pushed Back', teaser: 'The National Union of Mineworkers strikes as tens and Van Halen releases their sixth studio album 1984 shaped the year with organised civic demand.' },
  { year: 1985, hook: 'Tension Kept Breaking Loose', teaser: 'The Provisional Irish Republican Army carries out and 1985 Algarrobo earthquake shaped the year with war and abrupt reversals.' },
  { year: 1986, hook: 'Conflict Never Sat Still', teaser: 'Ugandan Bush War and Space Shuttle Challenger disaster shaped the year with conflict and volatile turns.' },
  { year: 1987, hook: 'Tension Broke Into the Open', teaser: 'Black Monday rattled markets, the First Intifada erupted after unrest at Gaza\'s edge, and the Great March in Washington made civil rights impossible to push aside.' },
  { year: 1988, hook: 'The Front Kept Moving', teaser: 'Soviet–Afghan War and 1988 Black Sea bumping incident shaped the year with war shaping the calendar.' },
  { year: 1989, hook: 'The Year Refused a Pattern', teaser: 'Former Ugandan dictator Idi Amin is expelled and Socialist Autonomous Province of Kosovo shaped the year with unpredictable turns.' },
  { year: 1990, hook: 'Power Turned Harder', teaser: 'Lebanese Civil War and League of Communists of Yugoslavia shaped the year with hard power and unstable order.' },
  { year: 1991, hook: 'An Order Came Apart', teaser: 'As the Soviet Union was dissolved and Ukraine voted for independence, war in Yugoslavia and violence in East Timor showed how unstable the post-Cold War opening could be.' },
  { year: 1992, hook: 'Conflict Never Sat Still', teaser: 'Air Inter Flight 148, an Airbus A320-111, crashes and Socialist Federal Republic of Yugoslavia shaped the year with conflict and volatile turns.' },
  { year: 1993, hook: 'The Public Imagination Shifted', teaser: 'January 1993 airstrikes on Iraq and United Nations Security Council Resolution 808 shaped the year with a visible shift in public life.' },
  { year: 1994, hook: 'The Balance Broke Open', teaser: 'U and Academy Award for Best Picture shaped the year with warfare and reshaped authority.' },
  { year: 1995, hook: 'The Streets Refused Silence', teaser: 'International Criminal Tribunal for the former Yugoslavia and The World Youth Day 1995 festival is held shaped the year with public pressure.' },
  { year: 1996, hook: 'The Year Refused Calm', teaser: 'Two suicide bombs explode in Israel, killing 32 and Democratic Republic of the Congo shaped the year with military pressure and persistent instability.' },
  { year: 1997, hook: 'Rights Moved to the Fore', teaser: 'Two of the three islands of the Union and Yasser Arafat returns to Hebron after more than shaped the year with rights moving into full view.' },
  { year: 1998, hook: 'The Year Refused a Pattern', teaser: 'United Nations Transitional Administration for Eastern Slavonia, Baranja and The Lunar Prospector spacecraft is launched into orbit shaped the year with unpredictable turns.' },
  { year: 1999, hook: 'Nothing Held Still for Long', teaser: '1999 Oklahoma tornado outbreak: a devastating tornado, rated and Pluto moves along its eccentric orbit further from shaped the year with constant instability.' },
  { year: 2000, hook: 'The Story Kept Swerving', teaser: 'A summit meeting takes place at Camp David and A rare century leap year date occurs shaped the year with events refusing a neat pattern.' },
  { year: 2001, hook: 'Shock Kept Arriving', teaser: 'A self-immolation incident takes place in Tiananmen Square and The 2001 insurgency in Macedonia begins when shaped the year with repeated shock and sudden turns.' },
  { year: 2002, hook: 'The Public Pushed Back', teaser: 'The Euro is introduced as the official physical and UNITA guerrilla leader Jonas Savimbi is killed shaped the year with organised civic demand.' },
  { year: 2003, hook: 'Rights Moved to the Fore', teaser: 'The Federal Republic of Yugoslavia is renamed and Space Shuttle Columbia disaster shaped the year with rights moving into full view.' },
  { year: 2004, hook: 'Power Moved Quickly', teaser: 'The 2004 Greek legislative election is held and The Iranian government under President Mohammad Khatami approved shaped the year with political realignment.' },
  { year: 2005, hook: 'Nothing Held Still for Long', teaser: 'The Constitution of Chile is heavily amended, eliminating and Eris, the most massive known dwarf planet shaped the year with constant instability.' },
  { year: 2006, hook: 'Tension Kept Breaking Loose', teaser: '2006 al-Askari mosque bombing: Explosions occur and A stampede during the Stoning of the Devil shaped the year with war and abrupt reversals.' },
  { year: 2007, hook: 'The Year Refused a Pattern', teaser: 'The 2007 Greensburg tornado moves through Kiowa County and Boston, United States faces a hoax bomb scare shaped the year with unpredictable turns.' },
  { year: 2008, hook: 'The Year Refused Calm', teaser: 'WikiLeaks releases allegations of illegal activities carried out and Venezuela and Ecuador move troops to the Colombian shaped the year with military pressure and persistent instability.' },
  { year: 2009, hook: 'Tension Kept Breaking Loose', teaser: 'Colgan Air Flight 3407 crashes in Clarence Center and The first block of the blockchain shaped the year with war and abrupt reversals.' },
  { year: 2010, hook: 'Conflict Set the Pace', teaser: 'Angolan Civil War and Supreme Council for the Restoration of Democracy shaped the year with military escalation.' },
  { year: 2011, hook: 'The Public Pushed Back', teaser: 'Tunisian street vendor Mohamed Bouazizi dies after setting and Shooting of Felani Khatun shaped the year with organised civic demand.' },
  { year: 2012, hook: 'Rights Moved to the Fore', teaser: '2015 Romanian protests and Wang Lijun incident shaped the year with rights moving into full view.' },
  { year: 2013, hook: 'A Year of Reach and Rupture', teaser: 'Typhoon Haiyan and the Bohol earthquake brought devastating force, even as India\'s Mars Orbiter Mission and Marmaray pointed to a world still stretching its ambitions.' },
  { year: 2014, hook: 'Authority Changed Hands', teaser: 'Revolution of Dignity and 2014 Kunming attack shaped the year with authority shifting in plain sight.' },
  { year: 2015, hook: 'Tension Kept Breaking Loose', teaser: 'Charlie Hebdo shooting and A Boko Haram and Islamic State assault shaped the year with war and abrupt reversals.' },
  { year: 2016, hook: 'Nature Hit Without Warning', teaser: '2016 Nagorno-Karabakh clashes: Clashes occur along the Nagorno-Karabakh and The International Consortium of Investigative Journalists shaped the year with sudden pressure.' },
  { year: 2017, hook: 'Nothing Held Still for Long', teaser: 'Turkish Airlines Flight 6491, a cargo flight en and 2016 Gambian presidential election shaped the year with constant instability.' },
  { year: 2018, hook: 'Instability Came in Waves', teaser: 'At 8:08 AM HST, an inbound missile alert and A total lunar eclipse takes place, the 49th shaped the year with pressure without much warning.' },
  { year: 2019, hook: 'Power Moved Quickly', teaser: 'Intermediate-Range Nuclear Forces Treaty and Ethiopian Airlines Flight 302, a Boeing 737 MAX shaped the year with political realignment.' },
  { year: 2020, hook: 'The World Went Indoors', teaser: 'A pandemic froze borders, emptied streets, and reshaped daily life, while market panic and mass protest showed that crisis would not quiet public demands.' },
  { year: 2021, hook: 'Public Pressure Held', teaser: 'January 6 United States Capitol attack and Idriss Déby, President of Chad, is killed shaped the year with collective pressure and civic change.' },
  { year: 2022, hook: 'The Year Refused a Pattern', teaser: 'A nationwide state of emergency is declared and World No shaped the year with unpredictable turns.' },
  { year: 2023, hook: 'Nothing Held Still for Long', teaser: 'Croatia adopts the euro and joins the Schengen and Cyclone Freddy forms in the Indian Ocean shaped the year with constant instability.' },
  { year: 2024, hook: 'The Public Mood Shifted', teaser: '2024 Austrian legislative election and 2024 Bangladeshi general election shaped the year with cultural momentum and political rearrangement.' },
  { year: 2025, hook: 'Public Life Changed Shape', teaser: 'National History Museum of Romania and 2025 Belarusian presidential election shaped the year with cultural change and political pressure.' },
  { year: 2026, hook: 'The Public Imagination Shifted', teaser: 'Operation Arctic Endurance is launched by Denmark, with and The United States launches several airstrikes on multiple shaped the year with a visible shift in public life.' },
] as const satisfies ReadonlyArray<{
  year: number;
  hook: string;
  teaser: string;
}>;
