#!/bin/bash
# Historiq Pro A/B Test — Subscription Localizations
# Weekly ID: 6762065299 | Yearly AB ID: 6762065221
# Çalıştır: bash docs/aso/pricing/raw-data/apply-ab-localizations.sh

set -e

WEEKLY_ID="6762065299"
YEARLY_ID="6762065221"

echo "=== WEEKLY LOCALIZATIONS ==="

asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "en-US" --name "Historiq Pro Weekly" --description "Unlock Historiq Pro. Cancel anytime."
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "en-GB" --name "Historiq Pro Weekly" --description "Unlock Historiq Pro. Cancel anytime."
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "en-AU" --name "Historiq Pro Weekly" --description "Unlock Historiq Pro. Cancel anytime."
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "en-CA" --name "Historiq Pro Weekly" --description "Unlock Historiq Pro. Cancel anytime."
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "de-DE" --name "Historiq Pro Wöchentlich" --description "Historiq Pro testen – ohne Bindung."
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "fr-FR" --name "Historiq Pro Hebdomadaire" --description "Historiq Pro sans engagement."
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "fr-CA" --name "Historiq Pro Hebdomadaire" --description "Historiq Pro sans engagement."
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "nl-NL" --name "Historiq Pro Wekelijks" --description "Historiq Pro zonder verplichting."
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "sv" --name "Historiq Pro Veckovis" --description "Historiq Pro utan åtagande."
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "ja" --name "Historiq Pro 週払いプラン" --description "気軽にHistoriq Proをお試しください"
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "ko" --name "Historiq Pro 주간" --description "부담 없이 Historiq Pro를 이용하세요"
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "ar-SA" --name "Historiq Pro أسبوعي" --description "جرّب Historiq Pro. إلغاء في أي وقت"
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "pl" --name "Historiq Pro Tygodniowy" --description "Historiq Pro bez zobowiązań."
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "es-MX" --name "Historiq Pro Semanal" --description "Historiq Pro sin compromiso."
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "es-ES" --name "Historiq Pro Semanal" --description "Historiq Pro sin compromiso."
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "pt-BR" --name "Historiq Pro Semanal" --description "Historiq Pro sem compromisso."
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "pt-PT" --name "Historiq Pro Semanal" --description "Historiq Pro sem compromisso."
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "th" --name "Historiq Pro รายสัปดาห์" --description "ลอง Historiq Pro ไม่มีข้อผูกมัด"
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "tr" --name "Historiq Pro Haftalık" --description "Uzun vadeli taahhüt yok. İptal et."
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "hi" --name "Historiq Pro साप्ताहिक" --description "बिना प्रतिबद्धता के Historiq Pro"
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "id" --name "Historiq Pro Mingguan" --description "Historiq Pro tanpa komitmen."
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "no" --name "Historiq Pro Ukentlig" --description "Historiq Pro uten forpliktelse."
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "ro" --name "Historiq Pro Săptămânal" --description "Historiq Pro fără angajamente."
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "hr" --name "Historiq Pro Tjedno" --description "Historiq Pro bez obveza."
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "fi" --name "Historiq Pro Viikoittain" --description "Historiq Pro ilman sitoumuksia."
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "he" --name "Historiq Pro שבועי" --description "Historiq Pro ללא התחייבות."
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "ca" --name "Historiq Pro Setmanal" --description "Historiq Pro sense compromís."
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "cs" --name "Historiq Pro Týdně" --description "Historiq Pro bez závazků."
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "el" --name "Historiq Pro Εβδομαδιαίο" --description "Historiq Pro χωρίς δέσμευση."
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "hu" --name "Historiq Pro Heti" --description "Historiq Pro kötelezettség nélkül."
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "ms" --name "Historiq Pro Mingguan" --description "Historiq Pro tanpa komitmen."
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "it" --name "Historiq Pro Settimanale" --description "Historiq Pro senza impegni."
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "da" --name "Historiq Pro Ugentlig" --description "Historiq Pro uden forpligtelse."
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "zh-Hans" --name "Historiq Pro 周度版" --description "无承诺，随时体验Historiq Pro"
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "zh-Hant" --name "Historiq Pro 週費版" --description "無承諾，隨時體驗Historiq Pro"
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "ru" --name "Historiq Pro Еженедельно" --description "Historiq Pro без обязательств."
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "sk" --name "Historiq Pro Týždenne" --description "Historiq Pro bez záväzkov."
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "uk" --name "Historiq Pro Щотижня" --description "Historiq Pro без зобов'язань."
asc subscriptions localizations create --subscription-id $WEEKLY_ID --locale "vi" --name "Historiq Pro Hàng Tuần" --description "Historiq Pro không ràng buộc."

echo "✓ Weekly localizations done (40 locales)"

echo ""
echo "=== YEARLY AB LOCALIZATIONS ==="

asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "en-US" --name "Historiq Pro Annual" --description "Best value – save 68% vs weekly"
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "en-GB" --name "Historiq Pro Annual" --description "Best value – save 63% vs weekly"
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "en-AU" --name "Historiq Pro Annual" --description "Best value – save 63% vs weekly"
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "en-CA" --name "Historiq Pro Annual" --description "Best value – save 68% vs weekly"
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "de-DE" --name "Historiq Pro Jährlich" --description "Bestes Angebot – 66 % vs wöchentlich"
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "fr-FR" --name "Historiq Pro Annuel" --description "Meilleur prix – 66 % vs hebdomadaire"
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "fr-CA" --name "Historiq Pro Annuel" --description "Meilleur prix – 68 % vs hebdomadaire"
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "nl-NL" --name "Historiq Pro Jaarlijks" --description "Beste waarde – 66% vs wekelijks"
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "sv" --name "Historiq Pro Årsvis" --description "Bästa värde – spara 67 % vs veckovis"
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "ja" --name "Historiq Pro 年額プラン" --description "週払いより68%お得な年額プラン"
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "ko" --name "Historiq Pro 연간" --description "주간 대비 67% 절약하는 최고의 선택"
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "ar-SA" --name "Historiq Pro سنوي" --description "أفضل قيمة – وفّر 67٪ vs الأسبوعي"
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "pl" --name "Historiq Pro Roczny" --description "Najlepsza wartość – 68 % vs tygodniowy"
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "es-MX" --name "Historiq Pro Anual" --description "Mejor precio – ahorra 67 % vs semanal"
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "es-ES" --name "Historiq Pro Anual" --description "Mejor precio – ahorre 63 % vs semanal"
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "pt-BR" --name "Historiq Pro Anual" --description "Melhor custo-benefício – 68% vs sem."
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "pt-PT" --name "Historiq Pro Anual" --description "Melhor valor – poupe 64% vs semanal"
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "th" --name "Historiq Pro รายปี" --description "ประหยัด 63% เทียบกับรายสัปดาห์"
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "tr" --name "Historiq Pro Yıllık" --description "En iyi fiyat – haftalığa göre %67 tasarruf"
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "hi" --name "Historiq Pro वार्षिक" --description "साप्ताहिक से 67% बचाएं – सर्वश्रेष्ठ"
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "id" --name "Historiq Pro Tahunan" --description "Nilai terbaik – hemat 62% vs mingguan"
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "no" --name "Historiq Pro Årlig" --description "Beste verdi – spar 66 % vs ukentlig"
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "ro" --name "Historiq Pro Anual" --description "Cea mai bună valoare – 68% vs săpt."
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "hr" --name "Historiq Pro Godišnje" --description "Najbolja vrijednost – 64 % vs tjedno"
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "fi" --name "Historiq Pro Vuosittain" --description "Paras arvo – säästä 64 % vs viikko"
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "he" --name "Historiq Pro שנתי" --description "הערך הטוב ביותר – חסוך 68% vs שבועי"
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "ca" --name "Historiq Pro Anual" --description "Millor preu – estalvia 63% vs setmanal"
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "cs" --name "Historiq Pro Ročně" --description "Nejlepší hodnota – 67 % vs týdně"
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "el" --name "Historiq Pro Ετήσιο" --description "Καλύτερη αξία – 64% έναντι εβδομ."
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "hu" --name "Historiq Pro Éves" --description "Legjobb ár – takarítson meg 68%-ot"
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "ms" --name "Historiq Pro Tahunan" --description "Nilai terbaik – jimat 66% vs mingguan"
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "it" --name "Historiq Pro Annuale" --description "Miglior valore – 66% vs settimanale"
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "da" --name "Historiq Pro Årlig" --description "Bedste værdi – spar 68 % vs ugentlig"
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "zh-Hans" --name "Historiq Pro 年度版" --description "最佳价值 – 比周付节省68%"
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "zh-Hant" --name "Historiq Pro 年費版" --description "最佳價值 – 比週付節省68%"
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "ru" --name "Historiq Pro Ежегодно" --description "Лучшая цена – экономия 67% vs неделя"
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "sk" --name "Historiq Pro Ročne" --description "Najlepšia hodnota – 64% vs týždenne"
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "uk" --name "Historiq Pro Щороку" --description "Найкраща ціна – 68% економія vs тиждень"
asc subscriptions localizations create --subscription-id $YEARLY_ID --locale "vi" --name "Historiq Pro Hàng Năm" --description "Tiết kiệm 66% so với gói tuần"

echo "✓ Yearly AB localizations done (40 locales)"
echo ""
echo "=== TAMAMLANDI: 80 lokalizasyon eklendi ==="
