import { Platform, StyleSheet } from 'react-native';

import { lightTheme, radius as radiusScale, spacing as spacingScale } from '@/theme';

const theme = lightTheme;
const { colors } = theme;
const accentColor = colors.accentPrimary;
const serifFamily = Platform.select({ ios: 'Times New Roman', android: 'serif', default: 'serif' });
const sansFamily = Platform.select({ ios: 'System', android: 'sans-serif', default: 'System' });

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.appBackground,
  },
  header: {
    paddingHorizontal: spacingScale.lg,
    paddingTop: spacingScale.sm,
    paddingBottom: spacingScale.md,
    backgroundColor: colors.headerBackground,
    gap: spacingScale.xs,
  },
  headerTop: {
    minHeight: 36,
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerBackButton: {
    width: 36,
    height: 36,
    borderRadius: radiusScale.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerBackButtonPressed: {
    opacity: 0.75,
  },
  headerBackPlaceholder: {
    width: 36,
    height: 36,
  },
  headerBackIcon: {
    fontSize: 20,
    color: colors.textInverse,
  },
  progressBarTrack: {
    height: 6,
    width: '100%',
    backgroundColor: colors.progressTrack,
    borderRadius: radiusScale.pill,
    marginTop: spacingScale.xs,
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: accentColor,
    borderRadius: radiusScale.pill,
  },
  contentWrapper: {
    flex: 1,
    borderTopLeftRadius: radiusScale.xl,
    borderTopRightRadius: radiusScale.xl,
    backgroundColor: colors.screen,
    paddingHorizontal: spacingScale.xl,
    paddingTop: spacingScale.lg,
    paddingBottom: spacingScale.xxl,
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacingScale.lg,
    paddingHorizontal: spacingScale.xl,
    paddingVertical: spacingScale.card,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.borderSubtle,
    backgroundColor: colors.screen,
  },
  primaryButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: accentColor,
    paddingVertical: spacingScale.lg,
    borderRadius: radiusScale.pill,
    shadowColor: colors.shadowColor,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 18,
    elevation: 4,
  },
  primaryButtonDisabled: {
    backgroundColor: colors.borderSubtle,
    shadowOpacity: 0,
  },
  primaryButtonPressed: {
    transform: [{ scale: 0.98 }],
  },
  primaryButtonText: {
    color: colors.surface,
    fontWeight: '600',
    fontSize: 17,
    letterSpacing: 0.2,
    fontFamily: sansFamily,
  },
  primaryButtonTextDisabled: {
    color: colors.textSecondary,
  },
  secondaryButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacingScale.lg,
    borderRadius: radiusScale.pill,
    borderWidth: 1,
    borderColor: colors.borderSubtle,
    backgroundColor: colors.surface,
  },
  pressedButton: {
    opacity: 0.9,
  },
  secondaryButtonText: {
    color: accentColor,
    fontWeight: '600',
    fontFamily: sansFamily,
  },
  disabledButton: {
    opacity: 0.5,
  },
  disabledButtonText: {
    color: colors.textTertiary,
  },
  stepScroll: {
    paddingBottom: spacingScale.xxl,
    gap: spacingScale.xl,
  },
  welcomeScroll: {
    paddingBottom: spacingScale.xxl,
    gap: spacingScale.xxl,
  },
  heroMasthead: {
    alignItems: 'center',
    gap: spacingScale.lg,
    paddingTop: spacingScale.md,
  },
  heroGreeting: {
    textAlign: 'center',
    color: colors.textPrimary,
    fontSize: 30,
    lineHeight: 36,
    fontFamily: serifFamily,
    letterSpacing: -0.6,
  },
  heroBody: {
    textAlign: 'center',
    color: colors.textSecondary,
    fontSize: 16,
    lineHeight: 24,
    fontFamily: sansFamily,
  },
  heroActions: {
    width: '100%',
    gap: spacingScale.md,
  },
  heroFootnote: {
    textAlign: 'center',
    color: colors.textTertiary,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: sansFamily,
  },
  ghostLink: {
    color: accentColor,
    fontWeight: '600',
    textAlign: 'center',
    fontFamily: sansFamily,
  },
  section: {
    gap: spacingScale.sm,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.textPrimary,
    fontFamily: sansFamily,
  },
  sectionCopy: {
    fontSize: 15,
    lineHeight: 22,
    color: colors.textSecondary,
    fontFamily: sansFamily,
  },
  stepTitle: {
    fontSize: 26,
    lineHeight: 32,
    color: colors.textPrimary,
    fontFamily: serifFamily,
    letterSpacing: -0.4,
  },
  stackGap: {
    gap: spacingScale.md,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: radiusScale.lg,
    padding: spacingScale.xl,
    gap: spacingScale.sm,
    shadowColor: colors.shadowColor,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 20,
    elevation: 2,
  },
  cardSelected: {
    borderWidth: 1,
    borderColor: accentColor,
    shadowOpacity: 0.12,
  },
  cardPressed: {
    transform: [{ scale: 0.99 }],
  },
  cardTitle: {
    fontSize: 16,
    color: colors.textPrimary,
    fontWeight: '600',
    fontFamily: sansFamily,
  },
  cardHint: {
    fontSize: 13,
    color: accentColor,
    fontFamily: sansFamily,
  },
  cardMeta: {
    fontSize: 13,
    color: colors.textTertiary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    fontFamily: sansFamily,
  },
  helperText: {
    fontSize: 13,
    color: colors.textTertiary,
    fontFamily: sansFamily,
  },
  inlineBackLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacingScale.xs,
    marginTop: spacingScale.sm,
  },
  inlineBackLinkText: {
    color: colors.textSecondary,
    fontSize: 14,
    fontFamily: sansFamily,
  },
  errorText: {
    fontSize: 12,
    color: '#dc2626',
    fontFamily: sansFamily,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.borderSubtle,
    paddingHorizontal: spacingScale.lg,
    paddingVertical: spacingScale.sm,
    borderRadius: radiusScale.md,
    fontSize: 16,
    color: colors.textPrimary,
    backgroundColor: colors.surface,
    fontFamily: sansFamily,
  },
  inlineButtonsRow: {
    flexDirection: 'row',
    gap: spacingScale.md,
  },
  inlinePrimaryButton: {
    alignSelf: 'flex-start',
    backgroundColor: accentColor,
    paddingHorizontal: spacingScale.card,
    paddingVertical: spacingScale.sm,
    borderRadius: radiusScale.pill,
  },
  inlinePrimaryButtonText: {
    color: colors.surface,
    fontSize: 15,
    fontWeight: '600',
    fontFamily: sansFamily,
  },
  optionChip: {
    paddingHorizontal: spacingScale.card,
    paddingVertical: spacingScale.sm,
    borderRadius: radiusScale.pill,
    marginRight: spacingScale.md,
    marginBottom: spacingScale.md,
  },
  optionChipOutlined: {
    borderWidth: 1,
    borderColor: colors.borderSubtle,
    backgroundColor: colors.surface,
  },
  optionChipActive: {
    backgroundColor: colors.accentSoft,
    borderColor: accentColor,
  },
  optionChipPressed: {
    opacity: 0.85,
  },
  optionChipText: {
    color: colors.textSecondary,
    fontSize: 15,
    fontWeight: '500',
    fontFamily: sansFamily,
  },
  optionChipTextActive: {
    color: accentColor,
  },
  chipRowWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  ghostButton: {
    alignSelf: 'flex-start',
    paddingHorizontal: spacingScale.lg,
    paddingVertical: spacingScale.sm,
    borderRadius: radiusScale.pill,
    backgroundColor: colors.accentSoft,
  },
  ghostButtonPressed: {
    opacity: 0.85,
  },
  ghostButtonText: {
    color: accentColor,
    fontWeight: '600',
    fontFamily: sansFamily,
  },
  inlineGhostButton: {
    alignSelf: 'flex-start',
    paddingHorizontal: spacingScale.lg,
    paddingVertical: spacingScale.sm,
    borderRadius: radiusScale.pill,
    borderWidth: 1,
    borderColor: colors.borderSubtle,
    backgroundColor: colors.surface,
  },
  inlineGhostButtonActive: {
    backgroundColor: colors.accentSoft,
    borderColor: accentColor,
  },
  inlineGhostButtonPressed: {
    opacity: 0.85,
  },
  inlineGhostButtonText: {
    color: colors.textSecondary,
    fontWeight: '500',
    fontFamily: sansFamily,
  },
  inlineGhostButtonTextActive: {
    color: accentColor,
  },
  carouselWrapper: {
    gap: spacingScale.lg,
    paddingBottom: spacingScale.xxl,
  },
  carouselPagerContainer: {
    width: '100%',
    paddingHorizontal: spacingScale.xl,
  },
  carouselPager: {
    width: '100%',
  },
  carouselPage: {
    flex: 1,
  },
  carouselScroll: {
    paddingBottom: spacingScale.sm,
  },
  carouselCard: {
    flexShrink: 0,
    backgroundColor: colors.surfaceSubtle,
    borderRadius: radiusScale.xl,
    overflow: 'hidden',
    shadowColor: colors.shadowColor,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.12,
    shadowRadius: 22,
    elevation: 4,
    width: '100%',
  },
  carouselCardSpacing: {
    marginRight: spacingScale.md,
  },
  previewCardImage: {
    ...StyleSheet.absoluteFillObject,
  },
  previewCardBlurBackdrop: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: '30%',
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    borderBottomLeftRadius: radiusScale.xl,
    borderBottomRightRadius: radiusScale.xl,
  },
  previewCardOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: spacingScale.xl,
    paddingBottom: spacingScale.xl,
    paddingTop: spacingScale.xl,
    height: '40%',
    justifyContent: 'flex-end',
    borderBottomLeftRadius: radiusScale.xl,
    borderBottomRightRadius: radiusScale.xl,
    backgroundColor: 'transparent',
  },
  previewCardTextGroup: {
    gap: spacingScale.xs,
    zIndex: 1,
  },
  previewCardHeading: {
    color: colors.surface,
    fontFamily: sansFamily,
    fontSize: 14,
    letterSpacing: 0.2,
    fontWeight: '500',
    textShadowColor: 'rgba(0, 0, 0, 0.8)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  previewCardSubheading: {
    color: colors.surface,
    fontFamily: serifFamily,
    fontSize: 20,
    lineHeight: 26,
    letterSpacing: -0.2,
    fontWeight: '600',
    textShadowColor: 'rgba(0, 0, 0, 0.8)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  paginationDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: spacingScale.sm,
  },
  paginationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.progressTrack,
  },
  paginationDotActive: {
    backgroundColor: accentColor,
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacingScale.sm,
    marginTop: spacingScale.sm,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: radiusScale.sm,
    borderWidth: 1,
    borderColor: colors.borderSubtle,
    backgroundColor: colors.surface,
  },
  checkboxChecked: {
    borderColor: accentColor,
    backgroundColor: colors.accentSoft,
  },
  checkboxLabel: {
    flex: 1,
    color: colors.textSecondary,
    fontSize: 14,
    fontFamily: sansFamily,
  },
  loadingState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: spacingScale.md,
    backgroundColor: colors.screen,
    paddingHorizontal: spacingScale.xl,
  },
  bulletList: {
    gap: spacingScale.xs,
  },
  bulletItem: {
    color: colors.textSecondary,
    fontSize: 14,
    fontFamily: sansFamily,
  },
  timeOptionGroup: {
    gap: spacingScale.md,
  },
  timeOption: {
    borderRadius: radiusScale.card,
    paddingVertical: spacingScale.lg,
    paddingHorizontal: spacingScale.xl,
    backgroundColor: colors.surfaceSubtle,
    borderWidth: 1,
    borderColor: 'transparent',
    alignItems: 'center',
  },
  timeOptionActive: {
    backgroundColor: colors.accentSoft,
    borderColor: accentColor,
    shadowColor: colors.shadowColor,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.12,
    shadowRadius: 18,
    elevation: 3,
  },
  timeOptionLabel: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.textPrimary,
    fontFamily: sansFamily,
  },
  timeOptionHint: {
    marginTop: spacingScale.xs,
    fontSize: 14,
    color: colors.textSecondary,
    fontFamily: sansFamily,
  },
  timeCustomCard: {
    marginTop: spacingScale.md,
    gap: spacingScale.sm,
  },
  permissionCard: {
    backgroundColor: colors.surface,
    borderRadius: radiusScale.lg,
    shadowColor: colors.shadowColor,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 4,
    overflow: 'hidden',
  },
  permissionImage: {
    width: '100%',
    aspectRatio: 796 / 536,
  },
  permissionTitle: {
    fontSize: 18,
    lineHeight: 24,
    fontFamily: sansFamily,
    color: colors.textPrimary,
    textAlign: 'center',
  },
  permissionHint: {
    fontSize: 13,
    color: colors.textSecondary,
    textAlign: 'center',
    fontFamily: sansFamily,
  },
  permissionActions: {
    flexDirection: 'row',
    gap: spacingScale.md,
  },
  permissionAction: {
    flex: 1,
    borderRadius: radiusScale.md,
    paddingVertical: spacingScale.md,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.borderSubtle,
  },
  permissionActionPrimary: {
    borderColor: accentColor,
    backgroundColor: colors.accentSoft,
  },
  permissionActionSecondary: {
    backgroundColor: colors.surface,
  },
  permissionActionLabel: {
    fontWeight: '600',
    color: colors.textPrimary,
    fontFamily: sansFamily,
  },
  formCard: {
    backgroundColor: colors.surface,
    borderRadius: radiusScale.lg,
    padding: spacingScale.xl,
    gap: spacingScale.md,
    shadowColor: colors.shadowColor,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
    elevation: 2,
  },
  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacingScale.md,
    marginTop: spacingScale.xl,
    marginBottom: spacingScale.lg,
  },
  dividerLine: {
    flex: 1,
    height: StyleSheet.hairlineWidth,
    backgroundColor: colors.borderSubtle,
  },
  dividerLabel: {
    color: colors.textTertiary,
    fontWeight: '600',
    fontFamily: sansFamily,
    letterSpacing: 0.6,
  },
  legalText: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
    fontFamily: sansFamily,
  },
  legalLink: {
    color: accentColor,
    fontWeight: '600',
  },
  socialButton: {
    borderRadius: radiusScale.pill,
    borderWidth: 1,
    borderColor: colors.borderSubtle,
    backgroundColor: colors.surface,
    paddingVertical: spacingScale.lg,
    paddingHorizontal: spacingScale.xl,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacingScale.md,
  },
  socialButtonSubtle: {
    backgroundColor: colors.surfaceSubtle,
  },
  socialButtonSelected: {
    borderColor: accentColor,
    backgroundColor: colors.accentSoft,
  },
  socialButtonPressed: {
    transform: [{ scale: 0.98 }],
  },
  socialButtonText: {
    color: colors.textPrimary,
    fontWeight: '600',
    fontFamily: sansFamily,
    textAlign: 'center',
  },
  socialButtonIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.surfaceSubtle,
    alignItems: 'center',
    justifyContent: 'center',
  },
  socialButtonIconSelected: {
    backgroundColor: colors.accentMuted,
  },
  socialButtonContent: {
    flex: 1,
    alignItems: 'center',
  },
  socialButtonSubcopy: {
    marginTop: spacingScale.xs,
    color: colors.textSecondary,
    fontSize: 12,
    fontFamily: sansFamily,
    textAlign: 'center',
  },
});

export { accentColor, colors, radiusScale, spacingScale, styles, theme };
